server {
    listen 80;
    resolver 127.0.0.11 valid=30s;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend_upstream backend:5000;
        proxy_pass http://$backend_upstream;
    }
}
